// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id, expires_at) VALUES (
    $1,
    $2,
    $3
) RETURNING token, user_id, created_at, updated_at, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt sql.NullTime
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT refresh_tokens.token, refresh_tokens.user_id, refresh_tokens.created_at, refresh_tokens.updated_at, refresh_tokens.expires_at, refresh_tokens.revoked_at, users.id, users.email, users.created_at, users.updated_at, users.hashed_password FROM refresh_tokens JOIN users ON users.id = refresh_tokens.user_id WHERE refresh_tokens.token = $1 LIMIT 1
`

type GetUserByTokenRow struct {
	Token          string
	UserID         uuid.UUID
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	ExpiresAt      sql.NullTime
	RevokedAt      sql.NullTime
	ID             uuid.UUID
	Email          string
	CreatedAt_2    sql.NullTime
	UpdatedAt_2    sql.NullTime
	HashedPassword string
}

func (q *Queries) GetUserByToken(ctx context.Context, token string) (GetUserByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByToken, token)
	var i GetUserByTokenRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ID,
		&i.Email,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.HashedPassword,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE refresh_tokens SET revoked_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE token = $1
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
